# This is a basic workflow to help you get started with Actions

name: china_list

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: download
        run: |-
          curl -s https://raw.githubusercontent.com/mayaxcn/china-ip-list/master/chnroute.txt > chnroute.txt
      
      - name: git push
        run: |-
          git diff
          git config user.name "Automated"
          git config user.email "---"
          git diff --quiet || (git add -A && git commit -m "Updated with latest")
          git push
          
