# This is a basic workflow to help you get started with Actions

name: china_list

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: download
        run: |-
          curl -s https://raw.githubusercontent.com/mayaxcn/china-ip-list/master/chnroute.txt > chnroute.txt
          curl -s https://raw.githubusercontent.com/mayaxcn/china-ip-list/master/chnroute.txt |sed -e 's/^/add address=/g' -e 's/$/ list=CNIP/g'|sed -e $'1i\\\n/ip firewall address-list' -e $'1i\\\nremove [/ip firewall address-list find list=CNIP]' -e $'1i\\\nadd address=10.0.0.0/8 list=CNIP comment=private-network' -e $'1i\\\nadd address=172.16.0.0/12 list=CNIP comment=private-network' -e $'1i\\\nadd address=192.168.0.0/16 list=CNIP comment=private-network' > chnroute.rsc
      
      - name: git push
        run: |-
          git diff
          git config user.name "Automated"
          git config user.email "---"
          git diff --quiet || (git add -A && git commit -m "Updated with latest")
          git push
          
